dist: trusty
sudo: required

language: java

jdk:
  - oraclejdk8

#php: 7.1

#services:
#  - mysql

os:
  - linux

before_script:
  # for debugging purposes
  - php --version
  - php-cgi --version
  - which php-cgi
  - chmod +x gradlew

script:
  # Regular test suite
  - ./gradlew test
  # Launch a server
  - ./gradlew clean tomcatRun
  - sudo netstat -nlp | grep :8093
  # Some debug to see if server has started
  - cat ./tomcat.log
  - sleep 10
  - cat ./tomcat.log
  - sudo netstat -nlp | grep :8093
  # debug travis
  - sudo netstat -nlp
  # Launch the soluble-japha test suite
  - sudo -E env "PATH=$PATH" ./.travis/run_soluble_japha_phpunit_tests.sh

after_failure:
  - cat ./tomcat.log

after_success:
  #- ./gradlew build jacocoTestReport
  - bash <(curl -s https://codecov.io/bash)


