dist: trusty
sudo: required

language: java

jdk:
  - oraclejdk8

#services:
#  - mysql

os:
  - linux

before_script:
  # for debugging purposes
  - php --version
  - chmod +x gradlew

script:
  - ./gradlew test
  - ./.travis/test_build_against_soluble_japha.sh
  - ./gradlew jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)


